apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: observability
spec:
#  strategy: allInOne
  strategy: production
#  allInOne:
#    image: jaegertracing/all-in-one:latest
#    options:
#      log-level: debug
#  storage:
#    type: memory
#    options:
#      memory:
#        max-traces: 100000
  storage:
    type: cassandra
    options: # <2>
      cassandra:
        servers: cassandra
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema: # <3>
      datacenter: "datacenter3"
      mode: "test"
    dependencies:
      enabled: true #turn the job deployment on and off
      schedule: "*/2 * * * *" #// cron expression for it to run
      sparkMaster: // spark master connection string, when empty spark runs in embedded local mode
      resources:
        requests:
          memory: 4096Mi
        limits:
          memory: 4096Mi      
  ingress:
    enabled: false
#  agent:
#    strategy: DaemonSet
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
